---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.star.local
  resources:
  - statefulautoscalers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.star.local
  resources:
  - statefulautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.star.local
  resources:
  - statefulautoscalers/status
  verbs:
  - get
  - patch
  - update
